name: jeeveeapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # for state management and page routing


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1 #for SVG
  slide_to_act: ^2.0.2   #For welcome page slide button
  firebase_core: ^3.6.0  # Ensure this is at least 3.6.0
  firebase_auth: ^5.3.0
  provider: ^6.1.2
  pinput: ^5.0.0
  firebase_app_check: ^0.3.1+3
  google_sign_in: ^6.2.1
  firebase_database: ^11.1.4  # Ensure this version matches firebase_core
  cloud_firestore: ^5.4.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  file_picker: ^8.1.2
  firebase_storage: ^12.3.1
  emoji_picker_flutter: ^3.1.0 
  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  flutter_notification_channel: ^3.1.0
  lottie: ^3.1.2
  google_generative_ai: ^0.4.6
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
 